openapi: 3.0.3
info:
  title: Swagger - OpenAPI 3.0
  description: AWS Lambda Golang PoC - OpenAPI definition
  contact:
    email: antonio@weffective.com
  version: 1.0.0
servers:
  - description: SwaggerHub API
    url: https://virtserver.swaggerhub.com/ANTONIO_22/golang-lambda-apigw-terraform-poc/1.0.0
  - description: Localstack API Gateway
    url: 'http://API_GATEWAY_ID.execute-api.localhost.localstack.cloud:4566/lambda'
  - description: App running locally as an independent service
    url: 'http://localhost:8080'
tags:
  - name: healthcheck
    description: Service healthcheck
  - name: user
    description: Operations about user
paths:
  /healthcheck:
    get:
      tags:
        - healthcheck
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                      id:
                        type: string
                      attributes:
                        type: object
                        properties:
                          service:
                            type: string
                          status:
                            type: string
        '500':
          description: server Error
      summary: System Healthcheck
  '/users/{id}':
    get:
      tags:
        - user
      summary: Find user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      type:
                        type: string
                      id:
                        type: string
                      attributes:
                        $ref: '#/components/schemas/User'
        '404':
          description: user not found
    delete:
      tags:
        - user
      summary: Delete user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: succesful operation
        '500':
          description: server Error
  /users:
    post:
      tags:
        - user
      summary: Create user
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: successful operation
        '500':
          description: server Error
    patch:
      tags:
        - user
      summary: Update user
      operationId: updateUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '204':
          description: successful operation
        '500':
          description: server Error
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: ULID
          example: 01J63630X372YYYR4CTFP1ZGGZ
        name:
          type: string
          format: string
          example: Miles Davis
        birthdate:
          type: string
          format: RFC3339
          example: '1984-11-25T17:04:05Z'